#!/usr/bin/env python
# -*- python -*-
__version__ = '$Revision: 1.1.1.1 $'
__date__ = '$Date: 2008/07/09 14:41:05 $'
__author__ = '$Author: ttaauu $'
__credit__ = ''

import sys
import os
import time
import signal

def main():
    '''
    if not os.access(daemon_file, os.F_OK):
        Es('no daemon found\n')
        return False
    '''
    while True:
        assert os.access(sys.argv[-1], os.F_OK)
        time.sleep(10)

def print_info(status):
    print '%s: %s' % (status, sys.argv[-1])
    fd = open(sys.argv[-1])
    cmd = fd.readlines()
    fd.close()
    fd = os.popen(''.join(filter(lambda x: '/usr/bin/printf' in x, cmd)))
    print fd.read()

def good(signum, frame):
    print_info('Good')
    sys.exit(0)

def bad(signum, frame):
    print_info('Bad')
    sys.exit(1)

if __name__ == '__main__':
    signal.signal(signal.SIGUSR1, good)
    signal.signal(signal.SIGUSR2, bad)
    main()
