#!/usr/bin/env python

# Copyright (c) 2009 by Kenjiro Taura. All rights reserved.
# Copyright (c) 2008 by Kenjiro Taura. All rights reserved.
# Copyright (c) 2007 by Kenjiro Taura. All rights reserved.
# Copyright (c) 2006 by Kenjiro Taura. All rights reserved.
# Copyright (c) 2005 by Kenjiro Taura. All rights reserved.
#
# THIS MATERIAL IS PROVIDED AS IS, WITH ABSOLUTELY NO WARRANTY 
# EXPRESSED OR IMPLIED.  ANY USE IS AT YOUR OWN RISK.
# 
# Permission is hereby granted to use or copy this program
# for any purpose,  provided the above notices are retained on all 
# copies. Permission to modify the code and to distribute modified
# code is granted, provided the above notices are retained, and
# a notice that the code was modified is included with the above
# copyright notice.
#
# $Header: /cvsroot/gxp/gxp3/gxpc,v 1.3 2009/06/06 14:06:22 ttaauu Exp $
# $Name:  $
#

try:
    import sys
    import gxpc

    if __name__ == "__main__":
        sys.exit(gxpc.cmd_interpreter().main(sys.argv))
except KeyboardInterrupt,e:
    pass

    
# $Log: gxpc,v $
# Revision 1.3  2009/06/06 14:06:22  ttaauu
# added headers and logs
#
